# fly.toml
app = "oneiron-helix"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  HELIX_DATA_DIR = "/data"
  HELIX_LOG_LEVEL = "info"
  HELIX_ACCESS_CONTROL = "true"
  HELIX_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[mounts]]
  source = "helix_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
