name: Core Database Tests In Production Mode

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'helix-macros/**'
      - 'helix-db/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  test:
    name: Test helix_engine in production mode
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      HELIX_API_KEY: "12345678901234567890123456789012"

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') || 'fallback' }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Run production tests
      run: |
        cd helix-db
        cargo test --release --lib --features production -- --skip concurrency_tests